variables:
  CUSTOMER: "openads"
  PLUGIN_NAME: "openads"
  PROJECT_ID: "418"
  POSTGRES_DB: "gis"
  POSTGRES_USER: "docker"
  POSTGRES_PASSWORD: "docker"
  POSTGRES_HOST: "db"

stages:
- Tests 🎳
- Package 📦
- Release 🚀

QGIS-3.16-PostGIS-2.5:
  stage: Tests 🎳
  image:
    name: $REGISTRY_URI/qgis/qgis:release-3_16
  services:
    - name: $REGISTRY_URI/postgis:11-2.5
      alias: db
  script:
    - mkdir /tests_directory/
    - ln -s ${CI_PROJECT_DIR}/${PLUGIN_NAME} /tests_directory
    - qgis_setup.sh ${PLUGIN_NAME}
    - cat .docker/postgis_connexions.ini >> /root/.local/share/QGIS/QGIS3/profiles/default/QGIS/QGIS3.ini
    # Patch the script because it uses an invalid redirection to non-existent /dev/tty
    # Run xvfb if necessary
    - nohup /usr/bin/Xvfb $DISPLAY -screen 0 1024x768x24 -ac +extension GLX +render -noreset -nolisten tcp &
    - ./.docker/qgis_testrunner.sh ${PLUGIN_NAME}.tests.runner.test_package
  variables:
     DISPLAY: ':99'
  tags:
    - factory-plain

QGIS-Latest-PostGIS-3.0:
  stage: Tests 🎳
  image:
    name: $REGISTRY_URI/qgis/qgis:latest
  services:
    - name: $REGISTRY_URI/postgis:13-3
      alias: db
  script:
    - mkdir /tests_directory/
    - ln -s ${CI_PROJECT_DIR}/${PLUGIN_NAME} /tests_directory
    - qgis_setup.sh ${PLUGIN_NAME}
    - cat .docker/postgis_connexions.ini >> /root/.local/share/QGIS/QGIS3/profiles/default/QGIS/QGIS3.ini
    # Patch the script because it uses an invalid redirection to non-existent /dev/tty
    # Run xvfb if necessary
    - nohup /usr/bin/Xvfb $DISPLAY -screen 0 1024x768x24 -ac +extension GLX +render -noreset -nolisten tcp &
    - ./.docker/qgis_testrunner.sh ${PLUGIN_NAME}.tests.runner.test_package
  variables:
     DISPLAY: ':99'
  tags:
    - factory-plain

Build-doc:
  stage: Tests 🎳
  rules:
    - if: '$CI_COMMIT_TAG != null'
      when: always
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual
  before_script:
    - pip3 install --user -r requirements/doc.txt
  script:
    - export PATH=$PATH:~/.local/bin
    - cp CHANGELOG.md docs/
    - cp CONTRIBUTING.md docs/
    - mkdocs build
  tags:
    - factory
  artifacts:
    expose_as: 'Documentation'
    paths:
      - build/

Upload-doc:
  stage: Release 🚀
  needs: ["Build-doc"]
  rules:
    - if: '$CI_COMMIT_TAG != null'
      when: always
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual
  script:
    - upload_folder_to_packages_server build/ private/${CUSTOMER}/docs
  tags:
    - fabric
