repos:
  # Fix end of files
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        exclude: 'docs/database'
      - id: end-of-file-fixer
        exclude: 'docs/database'
      - id: mixed-line-ending
        exclude: 'docs/database'
        args:
          - '--fix=lf'

  # Remove unused imports/variables
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args:
          - "--in-place"
          - "--remove-all-unused-imports"
          - "--remove-unused-variable"

  - repo: https://github.com/pycqa/flake8
    rev: '4.0.1'
    hooks:
     - id: flake8
    additional_dependencies: [flake8-docstrings, flake8-absolute-import, flake8-absolute-import, flake8-bugbear, flake8-builtins, flake8-isort, flake8-multiline-containers, flake8-mutable, flake8-pep3101, flake8-print, flake8-variables-names]

  # Sort imports
  - repo: https://github.com/pycqa/isort
    rev: "5.9.3"
    hooks:
      - id: isort
        args:
          - --profile
          - black

  # Black formatting
  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black
